SELECT DISTINCT T.NOME, T.ESTADO
FROM TIME T, UNIFORME U
WHERE T.NOME = U.TIME
  AND COR_PRINCIPAL = NULL;

SELECT DISTINCT T.NOME, T.ESTADO
FROM TIME T, UNIFORME U
WHERE T.NOME = U.TIME
    MINUS (SELECT DISTINCT T.NOME, T.ESTADO
            FROM TIME T, UNIFORME U
            WHERE T.NOME= U.TIME
            AND U.COR_PRINCIPAL != NULL);