-- @author João Villaça - 10724239
-- SCC0240 - Bases de Dados

-- 1)
SELECT T.NOME, T.ESTADO FROM TIME T
  INNER JOIN UNIFORME U ON (
    T.NOME = U.TIME
    AND U.TIPO = 'TITULAR')
  WHERE U.COR_PRINCIPAL IS NULL


-- 2)
SELECT J.NOME, J.DATA_NASC, J.TIME, T.ESTADO, P.DATA, P.LOCAL FROM JOGADOR J
  INNER JOIN TIME T
    ON (J.TIME = T.NOME)
  LEFT JOIN JOGA
    ON (JOGA.CLASSICO = 'S'
    AND (T.NOME = JOGA.TIME1
    OR T.NOME = JOGA.TIME2))
  LEFT JOIN PARTIDA P
    ON (JOGA.TIME1 = P.TIME1
    AND JOGA.TIME2 = P.TIME2);


-- 3)
SELECT COUNT(JOGO.CLASSICO) FROM PARTIDA P 
  INNER JOIN JOGA JOGO ON (
    JOGO.TIME1 = P.TIME1
    AND JOGO.TIME2 = P.TIME2)
  WHERE EXTRACT (MONTH FROM P.DATA) < 3;


-- 4)
SELECT EXTRACT(MONTH FROM P.DATA), COUNT(*) AS QTD_JOGOS FROM PARTIDA P
  INNER JOIN JOGA JOGO ON (
    JOGO.TIME1 = P.TIME1
    AND JOGO.TIME2 = P.TIME2
    AND JOGO.CLASSICO = 'S'
  )
  WHERE EXTRACT(YEAR FROM P.DATA) = 2018
    GROUP BY EXTRACT(MONTH FROM P.DATA)
    ORDER BY QTD_JOGOS DESC;


-- 5)
SELECT T.NOME, T.ESTADO, T.SALDO_GOLS, EXTRACT(YEAR FROM P.DATA), COUNT(JOGO.CLASSICO) FROM TIME T 
  LEFT JOIN JOGA JOGO ON (
    JOGO.TIME1 = T.NOME
    OR JOGO.TIME2 = T.NOME
    AND JOGO.CLASSICO = 'S'
  )
  LEFT JOIN PARTIDA P ON (
    P.TIME1 = JOGO.TIME1
    AND P.TIME2 = JOGO.TIME2
  )
  GROUP BY EXTRACT(YEAR FROM P.DATA);


-- 6)


-- 7)
SELECT COUNT(*)
